---
unsupported:
- path:
    admin_api: betaSettings.cloudSqlInstances
    app_yaml: beta_settings.cloud_sql_instances
  severity: major
  reason: Cloud Run does not support TCP based CloudSQL instance configs.
- path:
    admin_api: volumes
    app_yaml: volumes
  severity: major
  reason: Cloud Run does not support tmpfs volume mounts.
- path:
    admin_api: network.forwardedPorts
    app_yaml: network.forwarded_ports
  severity: major
  reason: Cloud Run does not support port forwarding. No clients can connect to the app using the forwarded ports.
- path:
    admin_api: inboundServices
    app_yaml: inbound_services
  severity: major
  reason: Cloud Run does not support GAE bundled services.
- path:
    admin_api: handlers
    app_yaml: handlers
  severity: major
  reason: No support for routing based on url patterns.
- path:
    admin_api: errorHandlers
    app_yaml: error_handlers
  severity: major
  reason: No support for routing based on url patterns.
- path:
    admin_api: appEngineApis
    app_yaml: app_engine_apis
  severity: major
  reason: No App Engine bundled services.
- path:
    admin_api: buildEnvVariables
    app_yaml: build_env_variables
  severity: major
  reason: No support for passing environment vars to buildpacks at the time of building.
- path:
    admin_api: diskGb
    app_yaml: disk_size_gb
  severity: minor
  reason: No support for custom disk size.
range_limited:
- path:
    admin_api: resources.cpu
    app_yaml: resources.cpu
  range:
    max: 8
    min: 0
  severity: major
  reason: Cloud Run supports max 8 CPUs.
- path:
    admin_api: resources.memoryGb
    app_yaml: resources.memory_gb
  range:
    max: 32
    min: 0
  severity: major
  reason: Cloud Run supports max 32Gi of memory.
- path:
    admin_api: automaticScaling.minInstances
    app_yaml: automatic_scaling.min_instances
  range:
    max: 1000
    min: 0
  severity: major
  reason: Cloud Run supports automatic scaling values between 0 and 1000.
  flags:
  - --min-instances
- path:
    admin_api: automaticScaling.maxInstances
    app_yaml: automatic_scaling.max_instances
  range:
    max: 1000
    min: 0
  severity: major
  reason: Cloud Run supports automatic scaling values between 0 and 1000.
  flags:
  - --max-instances
- path:
    admin_api: automaticScaling.minNumInstances
    app_yaml: automatic_scaling.min_num_instances
  range:
    max: 1000
    min: 0
  severity: major
  reason: Cloud Run supports automatic scaling values between 0 and 1000.
  flags:
  - --min-instances
- path:
    admin_api: automaticScaling.maxNumInstances
    app_yaml: automatic_scaling.max_num_instances
  range:
    max: 1000
    min: 0
  severity: major
  reason: Cloud Run supports automatic scaling values between 0 and 1000.
  flags:
  - --max-instances
- path:
    admin_api: manualScaling.instances
    app_yaml: manual_scaling.instances
  range:
    max: 1000
    min: 0
  severity: major
  reason: Cloud Run supports manual scaling values between 0 and 1000.
  flags:
  - --min-instances
  - --max-instances
- path:
    admin_api: basicScaling.maxInstances
    app_yaml: basic_scaling.max_instances
  range:
    max: 1000
    min: 0
  severity: major
  reason: Cloud Run supports basic scaling values between 0 and 1000.
  flags:
  - --min-instances
  - --max-instances
value_limited:
- path:
    admin_api: runtimeConfig.pythonVersion
    app_yaml: runtime_config.python_version
  known_values:
    - 2
    - 3
  allowed_values:
    - 3
  severity: major
  reason: Cloud Run supports Python 3 runtime only.